import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

serve(async (req) => {
  // Webhooks are usually POST
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 })
  }

  try {
    // VAPI sends a JSON payload on call termination
    const payload = await req.json()
    
    // We only care about end-of-call report or function calls
    // Usually VAPI payload type is payload.message.type === 'end-of-call-report'
    
    // Validate secret token from VAPI to ensure the webhook is legit
    const vapiWebhookSecret = Deno.env.get('VAPI_WEBHOOK_SECRET')
    const signature = req.headers.get('x-vapi-secret')
    if (vapiWebhookSecret && signature !== vapiWebhookSecret) {
        return new Response('Unauthorized', { status: 401 })
    }

    const message = payload.message
    if (!message) return new Response('OK', { status: 200 })

    if (message.type === 'end-of-call-report' || message.type === 'function-call') {
        
        // Extract the metadata we passed when we initiated the call (guestId)
        const guestId = message.call?.metadata?.guestId || payload.call?.metadata?.guestId
        if (!guestId) return new Response('No guestId found', { status: 200 })

        // Extract the structured data generated by VAPI's extraction or function call
        // Assuming we set up an extraction schema in VAPI for { is_attending: boolean, guest_count: number }
        const extractedData = message.analysis?.extractedValues || message.functionCall?.parameters
        
        if (extractedData) {
            const isAttending = extractedData.is_attending
            const guestCount = extractedData.guest_count || 0
            
            const statusStr = isAttending ? 'confirmed' : 'declined'

            const supabaseAdmin = createClient(
                Deno.env.get('SUPABASE_URL') ?? '',
                Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
            )

            // Update database securely
            const eventId = message.call?.metadata?.eventId || payload.call?.metadata?.eventId

            const { error: updateError } = await supabaseAdmin
                .from('guests')
                .update({ 
                    status: statusStr, 
                    confirmed_guests: isAttending ? guestCount : 0,
                    notes: `Updated via VAPI logic.`
                })
                .eq('id', guestId)

            if (updateError) {
                console.error('Failed to update guest:', updateError)
                throw new Error('Database update failed')
            }

            // Log the call to the messages table
            if (eventId) {
                await supabaseAdmin.from('messages').insert({
                    event_id: eventId,
                    guest_id: guestId,
                    channel: 'voice',
                    message_text: `Call initiated. Status: ${statusStr}. Guests requested: ${guestCount}`,
                    reply_text: message.analysis?.summary || 'No transcript summary provided.',
                    status: 'replied'
                })
            }
        }
    }

    return new Response(JSON.stringify({ success: true }), { 
        headers: { 'Content-Type': 'application/json' },
        status: 200 
    })
  } catch (error) {
    console.error('Webhook error:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { 'Content-Type': 'application/json' },
      status: 500,
    })
  }
})
